stages:
- docker
- test
- publish

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CONTAINER_REGISTRY/taig-github/schelm
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

docker:
  stage: docker
  image: docker
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
  - docker pull $CONTAINER_IMAGE:latest || true
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF_NAME .
  - docker push $CONTAINER_IMAGE

test-format:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
  - sbt scalafmtCheckAll

test-artifacts:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
  - sbt -Dmode=strict playgroundJS/fastOptJS

test-docs:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
  - sbt makeMicrosite

publish-artifacts:
  stage: publish
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  only:
  - master
  - tags
  script:
  - sbt publishAndRelease

publish-docs:
  stage: publish
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  only:
  - tags
  script:
  - sbt publishMicrosite
