stages:
- docker
- test
- deploy

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CONTAINER_REGISTRY/taig-github/schelm
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CONTAINER_IMAGE

test-format:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
    - sbt -Dmode=strict scalafmtCheckAll

test-artifacts:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
    - sbt -Dmode=strict +playgroundJS/fastOptJS

test-docs:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
    - sbt -Dmode=strict website/makeMicrosite
    - mv website/target/site/ site/
  artifacts:
    expire_in: 1 month
    paths:
      - site/

publish-artifacts:
  stage: deploy
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  only:
    - master
    - tags
  script:
    - sbt -Dmode=strict publishAndRelease

pages:
  stage: deploy
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  only:
    # Should be set to "tags", but before a stable version is published, master
    # is more useful
    - master
  script:
    - mv site/ public/
  artifacts:
    paths:
      - public/
  dependencies:
    - test-docs
